version: '2'
services:
  webserver:
    image: phpstorm/php-71-apache-xdebug-26
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.iternal

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - volume_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123321
      MYSQL_DATABASE: php_db

volumes:
  volume_db: